### PR TITLE
style(markup) mainpage

### PR DESCRIPTION
**Pull request by soonmac**
1. markup main page(searchbar,theme recipe, lookup recipe)
2. add local font (1)
3. fix footer style
screencapture-localhost-3000-2022-04-24-02_26_20

### CODE REVIEW

**Comment by quangthan87** [comment]
excellent!

**Comment by quangthan87** [comment]
Just a small issue: there existed a "public" folder in root directory, as you created a new "public" folder in "pages", which is confusing

**Comment by soonmac** [comment]
> 

image
I moved the "public" folder into the "page" folder
Is this OK?

**Comment by quangthan87** [comment]
I don't know if your implementation is a good practice or not, but Next.js recommend to keep the "public" folder in root folder for [static file serving](https://nextjs.org/docs/basic-features/static-file-serving). So in my opinion, we should keep the "public" folder at root directory and serve the images as static file. As a result, we don't need to use next-images library.

**Comment by quangthan87** [comment]
Like this:

image

**Comment by soonmac** [comment]
> 

thank you!!! i'll fix it and merge!

**Pull request closed without merging**
